spring.application.name=predictdt
spring.profiles.active=dev
# Exibe as queries SQL no console
spring.jpa.show-sql=true
# Libera a conexão com o banco para outras requisições assim que a transação termina
spring.jpa.open-in-view=false